-- Instructor profile fields stored on users table.
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS class_level VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS province VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS parent_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS parent_phone VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS instagram VARCHAR(100);

